### ISSUE TITLE
[Bug] - Controlnet update (May 6, 2023) changed PNG metadata format which breaks MetaParser output

### ISSUE THREAD

**Issue by CCpt5** [stassius/MetaParser#3]
**Describe the bug**
The developers of Controlnet pushed an update today which changed the way Controlnet formats its PNG metadata. I ran a quick test and their change causes issues on the Metaparser output (Incorrect info for Controlnet items).

Their developer discussion on this topic/change: https://github.com/Mikubill/sd-webui-controlnet/issues/1180

**To Reproduce**
1. Update Controlnet
2. Output an image with Controlnet enabled
3. Open in Metaparser
4. Notice controlnet items are misaligned or incorrect 

**Expected behavior**

**Additional context**
Saw the post first and immediately assumed it would cause issues w/ MetaParser which it does seem to do. They breakdown the before and after Metadata changes which should indicate what needs to be adjusted code-wise. Thanks!

**Comment by stassius** [comment]
Thanks for the report. I was planning to parse quotes anyway, will fix it in the next update.

**Comment by stassius** [comment]
It was fixed with the last commit. Should work on both old and the new version of ControlNet.

**Comment by stassius** [comment]
It looks like you use Dynamic prompt extension. Its authors invented their own format of metadata, which is not compatible with A1111 one.  I contacted them, but they refused to fix it (don't know why). I just added the Template keyword to a blacklist, so it won't break the rest of the metadata. Check the last commit.

**Comment by CCpt5** [comment]
Eh, that makes sense, and I did see that "discussion". Oh well.

To be completely honest I do like the template line so I may end up sticking w/ the prior version at least for now. It's too bad I think their extension is the only way incorporate wildcards in prompts. I enjoy prompting w wildcards and running a bunch of generations in batch. 

Appreciate your time/updates!
